### ISSUE TITLE
Add support for users in Integration tests

### ISSUE THREAD

**Issue by ScholliYT** [WDWWW/aspnetcore-easy-testing#2]
Hi,

I would love to see a feature for using Authorization with ASP.NET Core Integration testing. I would like to be able to access Actions "blocked" by Authorize Attributes (with spcific Roles/Policies).

I already did some testing myself and couldn't get it working. Maybe you'll have more luck if interested :D

**Comment by enif-lee** [comment]
Yeah, that's good idea. I will investigate to support replacing fake `IAuthorizeHandler` and `IAuthenticationHandler` easily.

**Comment by enif-lee** [comment]
Hello, It's long time no see T__T

I just published new version package 3.1.2 with fake authentication handler feature with convenient methods.

Check out below documentation when you have free time.
 https://github.com/WDWWW/aspnetcore-easy-testing#fake-authentication-layer-of-aspnet-core

To fake authorization feature is on the road. I will lookup for authorization.
