### ISSUE TITLE
[RFC] Add feature to fake/replace authentication and authorization handlers 

### ISSUE THREAD

**Issue by enif-lee** [WDWWW/aspnetcore-easy-testing#3]
> Origin issue from #2 

### Draft API
```csharp

// Apply default authentication scheme if there is no scheme parameter.
SUT.AllowAuthentication("Scheme", new ClaimsPrincipal(/* ... */)
    .AllowAuthentication(new ClaimsPrincipal())
    .DenyAuthentication("Scheme")
    .DenyAutheitncation()
    .NoUserAuthentication()
    .NoUserAuthentication("Scheme")
    .ReplaceAuthenticationHandler<CustomFakeHandler>("Bearer", ServiceLifetime.Singleton)
    .FakeAuthentication(AuthenticationReulst.NoUser())
    .AllowAuthorization<CustomeRequirement>()
    .DenyAuthorization<CustomeRequirement>()
;
```

### Research note

Authentication 
- https://github.com/aspnet/Security/blob/master/src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs

Authorization
- https://github.com/unsafecode/AspNetCore/blob/master/src/Security/Authorization/Core/src/AuthorizationHandler.cs
- https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authorization/Core/src/IAuthorizationRequirement.cs
- https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authorization/Core/src/ClaimsAuthorizationRequirement.cs
- https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authorization/Core/src/RolesAuthorizationRequirement.cs

Similar libarary
- https://github.com/jabbera/aspnetcore-testing-role-handler

**Comment by ScholliYT** [comment]
If there is anything to test yet, please let me know.
